---
title: "p8105_hw2_ab6168"
output: github_document
date: "2025-09-24"
---

```{r setup, echo=FALSE, message = FALSE}
library(tidyverse)
```


##Problem 1
```{r}
#cleaning pols_month dataframe
pols_month_df = 
  read_csv("data/pols-month.csv") |> 
  separate(mon,
    into = c("year", "month","day"), sep = "-") |> 
  mutate(year = as.numeric(year),
    month = case_match(
      month,
      "01" ~ "jan",
      "02" ~ "feb",
      "03" ~ "mar",
      "04" ~ "apr",
      "05" ~ "may",
      "06" ~ "jun",
      "07" ~ "jul",
      "08" ~ "aug",
      "09" ~ "sep",
      "10" ~ "oct",
      "11" ~ "nov",
      "12" ~ "dec"),
    prez_gop = case_match(
      prez_gop,
      0 ~ "dem",
      1 ~ "gop"
    ),
    president = prez_gop) |> 
  select(-day,-prez_gop,-prez_dem)



#cleaning snp dataframe
snp_df = 
  read_csv("data/snp.csv") |> 
  separate(date,
    into = c("month", "day","year"), sep = "/") |> 
  mutate(year = as.numeric(year),
         year = case_when(
           year > 15 ~ year + 1900,
           year <= 15 ~ year + 2000
         ),
         month = case_match(
           month,
           "1" ~ "jan",
           "2" ~ "feb",
           "3" ~ "mar",
           "4" ~ "apr",
           "5" ~ "may",
           "6" ~ "jun",
           "7" ~ "jul",
           "8" ~ "aug",
           "9" ~ "sep",
           "10" ~ "oct",
           "11" ~ "nov",
           "12" ~ "dec")
        ) |> 
  select(-day) |> 
  relocate(year)




#cleaning unemployment dataframe
unemployment_df = 
  read_csv("data/unemployment.csv") |> 
  pivot_longer(
    cols = Jan:Dec,
    names_to = "month",
    values_to = "per_unemp"
  ) |> 
  mutate(month = tolower(month), 
           year = Year) |> 
  select(-Year) |> 
  relocate(year)

```


Joining datasets

```{r}
#merging `pols` and `snp` datasets
pols_snp_df =
  left_join(pols_month_df, snp_df, by = "year") 

#merging `unemployment` with result
fte_df =
  left_join(pols_snp_df, unemployment_df, by = "year")
```


